/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_dgl_com_androidfive_JniUtils */

#ifndef _Included_www_dgl_com_androidfive_JniUtils
#define _Included_www_dgl_com_androidfive_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_dgl_com_androidfive_JniUtils
 * Method:    getThreeDesKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_dgl_com_androidfive_JniUtils_getThreeDesKey
  (JNIEnv *, jclass);

/*
 * Class:     www_dgl_com_androidfive_JniUtils
 * Method:    getSqlKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_dgl_com_androidfive_JniUtils_getSqlKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
